<?php

namespace Proxies\__CG__\EAMBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContactoEmergencia extends \EAMBundle\Entity\ContactoEmergencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'numero', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'relacionPaciente', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'idPaciente', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'nombre', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'apellido', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'fechaAnhadido', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'id');
        }

        return array('__isInitialized__', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'numero', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'relacionPaciente', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'idPaciente', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'nombre', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'apellido', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'fechaAnhadido', '' . "\0" . 'EAMBundle\\Entity\\ContactoEmergencia' . "\0" . 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContactoEmergencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelacionPaciente($relacionPaciente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelacionPaciente', array($relacionPaciente));

        return parent::setRelacionPaciente($relacionPaciente);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelacionPaciente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelacionPaciente', array());

        return parent::getRelacionPaciente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPaciente($idPaciente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPaciente', array($idPaciente));

        return parent::setIdPaciente($idPaciente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPaciente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPaciente', array());

        return parent::getIdPaciente();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', array($apellido));

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', array());

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAnhadido($fechaAnhadido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAnhadido', array($fechaAnhadido));

        return parent::setFechaAnhadido($fechaAnhadido);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAnhadido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAnhadido', array());

        return parent::getFechaAnhadido();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
