login:
    path:    /
    defaults: { _controller: EAMBundle:Inicio:login }

login_check:
   path: /login_check
   defaults: { _controller: EAMBundle:Inicio:loginCheck }

Home:
    path:    /home
    defaults: { _controller: EAMBundle:Inicio:iniciar }

ajax_request:
    path:  /Empleado/ajax_
    defaults: { _controller: EAMBundle:Empleado:disponible }
    requirements:
          _method: POST

Nuevo_empleado:
    path:  /Empleado/nuevo
    defaults: { _controller: EAMBundle:Empleado:Nuevo }

Ver_empleados:
    path: /Empleado/mostrar
    defaults: { _controller: EAMBundle:Empleado:Mostrar }

Ver:
    path: /Empleado/detallesUsuario
    defaults: { _controller: EAMBundle:Empleado:Ver }

Elegir:
    path: /Empleado/opcion
    defaults: { _controller: EAMBundle:Empleado:Elegir }

Editar:
    path: /Empleado/edita/{id}
    defaults: { _controller: EAMBundle:Empleado:Editar }

Actualizar:
    path: /Empleado/actualiza/{id}
    defaults: { _controller: EAMBundle:Empleado:Actualizar }

Ayuda:
    path: /Ayuda
    defaults: {_controller: EAMBundle:Ayuda:Mostrar }

Bitacora:
    path: /registros
    defaults: { _controller: EAMBundle:Bitacora:Mostrar }

Nuevo_paciente:
    path: /nuevo_paciente
    defaults: { _controller: EAMBundle:Paciente:Nuevo }

Guardar_paciente:
    path: /guardar_paciente
    defaults: { _controller: EAMBundle:Paciente:Guardar }

logout:
   path: /logout

Nueva_cita:
    path: /cita/nueva/
    defaults: {_controller: EAMBundle:Cita:NuevaCita}

Mostrar_citas:
    path: /cita/vercitas/
    defaults: { _controller: EAMBundle:Cita:MostrarCitas }

Cita_elegir:
    path: /cita/{id}/opcion/
    defaults: { _controller: EAMBundle:Cita:Elegir }

Cita_editar:
    path: /cita/{id}/editar/
    defaults: { _controller: EAMBundle:Cita:EditarCita}

Cita_actualizar:
    path:  /cita/{id}/actualizar
    defaults: { _controller: "EAMBundle:Cita:ActualizarCita" }
