login:
    path:    /
    defaults: { _controller: EAMBundle:Inicio:login }

login_check:
   path: /login_check
   defaults: { _controller: EAMBundle:Inicio:loginCheck }

Home:
    path:    /home
    defaults: { _controller: EAMBundle:Inicio:iniciar }

Nuevo_empleado:
    path:    /nuevo
    defaults: { _controller: EAMBundle:Empleado:Nuevo }

Ver_empleados:
    path: /mostrar
    defaults: { _controller: EAMBundle:Empleado:Mostrar }
Ver:
    path: /detallesUsuario
    defaults: { _controller: EAMBundle:Empleado:Ver }

Elegir:
    path: /opcion
    defaults: { _controller: EAMBundle:Empleado:Elegir }

Editar:
    path: /edita/{id}
    defaults: { _controller: EAMBundle:Empleado:Editar }

Actualizar:
    path: /actualiza/{id}
    defaults: { _controller: EAMBundle:Empleado:Actualizar }

Nueva_cita:
    path: /nuevacita/
    defaults: {_controller: EAMBundle:Cita:NuevaCita}

logout:
   path: /logout
