login:
    path:    /
    defaults: { _controller: EAMBundle:Inicio:login }

login_check:
   path: /login_check
   defaults: { _controller: EAMBundle:Inicio:loginCheck }

Home:
    path:    /home
    defaults: { _controller: EAMBundle:Inicio:iniciar }

ajax_request:
    path:  /Empleado/ajax_
    defaults: { _controller: EAMBundle:Empleado:disponible }
    requirements:
          _method: POST

Nuevo_empleado:
    path:  /Empleado/nuevo
    defaults: { _controller: EAMBundle:Empleado:Nuevo }

Ver_empleados:
    path: /Empleado/mostrar
    defaults: { _controller: EAMBundle:Empleado:Mostrar }

Ver:
    path: /Empleado/detallesUsuario
    defaults: { _controller: EAMBundle:Empleado:Ver }

Elegir:
    path: /Empleado/opcion
    defaults: { _controller: EAMBundle:Empleado:Elegir }

Editar:
    path: /Empleado/edita/{id}
    defaults: { _controller: EAMBundle:Empleado:Editar }

Actualizar:
    path: /Empleado/actualiza/{id}
    defaults: { _controller: EAMBundle:Empleado:Actualizar }

Ayuda:
    path: /Ayuda
    defaults: {_controller: EAMBundle:Ayuda:Mostrar }

Bitacora:
    path: /registros
    defaults: { _controller: EAMBundle:Bitacora:Mostrar }

NuevoPaciente:
    path: /paciente/nuevo
    defaults: { _controller: EAMBundle:Paciente:Nuevo }

Buscar_Pacientes:
    path: /paciente/buscar
    defaults: { _controller:EAMBundle:Paciente:Buscar}

Ver_Paciente:
    path: /paciente/ver/{id}
    defaults: { _controller: EAMBundle:Paciente:Ver }

Editar_paciente:
    path: /paciente/editar/{id}
    defaults: { _controller: EAMBundle:Paciente:Editar}

Actualizar_Paciente:
    path: /paciente/actualizar/{id}
    defaults: { _controller: EAMBundle:Paciente:Actualizar}

Eliminar_Paciente:
    path: /paciente/elimiar/{id}
    defaults: { _controller: EAMBundle:Paciente:Eliminar}

logout:
   path: /logout

Nueva_cita:
    path: /cita/nueva/
    defaults: {_controller: EAMBundle:Cita:NuevaCita}

Mostrar_citas:
    path: /cita/vercitas/
    defaults: { _controller: EAMBundle:Cita:MostrarCitas }

Cita_eliminar:
    path: /cita/eliminar/{id}
    defaults: { _controller: EAMBundle:Cita:EliminarCita }

Cita_editar:
    path: /cita/editar/{id}/
    defaults: { _controller: EAMBundle:Cita:EditarCita}

Cita_actualizar:
    path:  /cita/actualizar/{id}
    defaults: { _controller: "EAMBundle:Cita:ActualizarCita" }

Cita_Visita:
    path:  /visita/nueva/{id}
    defaults: { _controller: "EAMBundle:Cita:Visita" }

Nueva_Visita:
    path:  /visita/nueva/
    defaults: { _controller: "EAMBundle:Visita:Nueva" }
